name: Deploy

on:
  release:
    types: [published] 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./src/
        server-dir: /lauto.com.ua/
    - name: Set permissions on .ftp-deploy-sync-state.json
        run: chmod 600 .ftp-deploy-sync-state.json
